# Generated by Django 2.1.5 on 2019-02-01 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_auto_20190131_2218'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='information',
            options={'ordering': ['request_date', 'request_number'], 'verbose_name': 'Information', 'verbose_name_plural': 'Informations'},
        ),
    ]
